// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Order book manager
type OrderBookEntry struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64  `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookEntry) Reset()         { *m = OrderBookEntry{} }
func (m *OrderBookEntry) String() string { return proto.CompactTextString(m) }
func (*OrderBookEntry) ProtoMessage()    {}
func (*OrderBookEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *OrderBookEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookEntry.Unmarshal(m, b)
}
func (m *OrderBookEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookEntry.Marshal(b, m, deterministic)
}
func (m *OrderBookEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookEntry.Merge(m, src)
}
func (m *OrderBookEntry) XXX_Size() int {
	return xxx_messageInfo_OrderBookEntry.Size(m)
}
func (m *OrderBookEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookEntry proto.InternalMessageInfo

func (m *OrderBookEntry) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderBookEntry) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderBookRequest struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookRequest) Reset()         { *m = OrderBookRequest{} }
func (m *OrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookRequest) ProtoMessage()    {}
func (*OrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *OrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookRequest.Unmarshal(m, b)
}
func (m *OrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookRequest.Merge(m, src)
}
func (m *OrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookRequest.Size(m)
}
func (m *OrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookRequest proto.InternalMessageInfo

func (m *OrderBookRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBookRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type OrderBookUpdatesRequest struct {
	Request              *OrderBookRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit                uint32            `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderBookUpdatesRequest) Reset()         { *m = OrderBookUpdatesRequest{} }
func (m *OrderBookUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookUpdatesRequest) ProtoMessage()    {}
func (*OrderBookUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *OrderBookUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookUpdatesRequest.Unmarshal(m, b)
}
func (m *OrderBookUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookUpdatesRequest.Merge(m, src)
}
func (m *OrderBookUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookUpdatesRequest.Size(m)
}
func (m *OrderBookUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookUpdatesRequest proto.InternalMessageInfo

func (m *OrderBookUpdatesRequest) GetRequest() *OrderBookRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *OrderBookUpdatesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderBookResponse struct {
	LastUpdate           int64             `protobuf:"varint,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Exchange             string            `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string            `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Asks                 []*OrderBookEntry `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*OrderBookEntry `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderBookResponse) Reset()         { *m = OrderBookResponse{} }
func (m *OrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*OrderBookResponse) ProtoMessage()    {}
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *OrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookResponse.Unmarshal(m, b)
}
func (m *OrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookResponse.Marshal(b, m, deterministic)
}
func (m *OrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookResponse.Merge(m, src)
}
func (m *OrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_OrderBookResponse.Size(m)
}
func (m *OrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookResponse proto.InternalMessageInfo

func (m *OrderBookResponse) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *OrderBookResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBookResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBookResponse) GetAsks() []*OrderBookEntry {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBookResponse) GetBids() []*OrderBookEntry {
	if m != nil {
		return m.Bids
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderBookEntry)(nil), "OrderBookEntry")
	proto.RegisterType((*OrderBookRequest)(nil), "OrderBookRequest")
	proto.RegisterType((*OrderBookUpdatesRequest)(nil), "OrderBookUpdatesRequest")
	proto.RegisterType((*OrderBookResponse)(nil), "OrderBookResponse")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0xfe, 0xda, 0xb7, 0xf8, 0x67, 0x41, 0xb4, 0xec, 0xe2, 0xa8, 0x97, 0x81, 0x50,
	0xa4, 0x9e, 0xbc, 0x0e, 0xf4, 0x26, 0x42, 0xc0, 0x9b, 0x20, 0xe9, 0x1a, 0x66, 0x59, 0xd7, 0x74,
	0x79, 0x53, 0xb0, 0x47, 0xbf, 0x92, 0x9f, 0x50, 0x9a, 0x6c, 0xa1, 0x73, 0xf6, 0xd6, 0x27, 0xef,
	0x93, 0xdf, 0xdb, 0xe7, 0x21, 0xe0, 0xeb, 0xba, 0x14, 0x18, 0x95, 0x4a, 0x6a, 0x19, 0x2e, 0xe0,
	0xec, 0x55, 0xa5, 0x42, 0x2d, 0xa4, 0x5c, 0x3f, 0x15, 0x5a, 0xd5, 0xf4, 0x12, 0x86, 0xa5, 0xca,
	0x96, 0x22, 0x20, 0x33, 0x32, 0x27, 0xcc, 0x0a, 0x3a, 0x85, 0x93, 0x6d, 0xc5, 0x0b, 0x9d, 0xe9,
	0x3a, 0xe8, 0x99, 0x81, 0xd3, 0xe1, 0x33, 0x5c, 0x38, 0x06, 0x13, 0xdb, 0x4a, 0xa0, 0x6e, 0xfc,
	0xe2, 0x6b, 0xf9, 0xc9, 0x8b, 0x95, 0x05, 0x79, 0xcc, 0x69, 0x7a, 0x05, 0x23, 0xac, 0x37, 0x89,
	0xcc, 0x0d, 0xc9, 0x63, 0x3b, 0x15, 0xbe, 0xc3, 0xb5, 0xe3, 0xbc, 0x95, 0x29, 0xd7, 0x02, 0xf7,
	0xb8, 0x3b, 0x18, 0x2b, 0xfb, 0x69, 0x68, 0x7e, 0x3c, 0x89, 0xfe, 0xae, 0x64, 0x7b, 0x47, 0x93,
	0x20, 0xcf, 0x36, 0x99, 0x36, 0xf8, 0x53, 0x66, 0x45, 0xf8, 0x43, 0x60, 0xd2, 0xba, 0x83, 0xa5,
	0x2c, 0x50, 0xd0, 0x1b, 0xf0, 0x73, 0x8e, 0xfa, 0xa3, 0x32, 0xfb, 0x0c, 0xbc, 0xcf, 0xa0, 0x39,
	0xb2, 0x7f, 0x70, 0x10, 0xa4, 0xd7, 0x19, 0xa4, 0xdf, 0x0e, 0x42, 0x6f, 0x61, 0xc0, 0x71, 0x8d,
	0xc1, 0x60, 0xd6, 0x9f, 0xfb, 0xf1, 0x79, 0x74, 0xd8, 0x30, 0x33, 0xc3, 0xc6, 0x94, 0x64, 0x29,
	0x06, 0xc3, 0x0e, 0x53, 0x33, 0x8c, 0xbf, 0x49, 0xab, 0xdb, 0x17, 0x5e, 0xf0, 0x95, 0x50, 0x34,
	0x06, 0xcf, 0x9d, 0xd1, 0xe3, 0x22, 0xa6, 0x34, 0x3a, 0xce, 0xf9, 0x08, 0xe3, 0x5d, 0xa5, 0x34,
	0x88, 0x3a, 0x5a, 0xfe, 0xef, 0xe2, 0x3d, 0x49, 0x46, 0xe6, 0xa5, 0x3c, 0xfc, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x35, 0x61, 0xd1, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderBookManagerClient is the client API for OrderBookManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderBookManagerClient interface {
	OrderBook(ctx context.Context, in *OrderBookRequest, opts ...grpc.CallOption) (*OrderBookResponse, error)
	Updates(ctx context.Context, in *OrderBookUpdatesRequest, opts ...grpc.CallOption) (OrderBookManager_UpdatesClient, error)
}

type orderBookManagerClient struct {
	cc *grpc.ClientConn
}

func NewOrderBookManagerClient(cc *grpc.ClientConn) OrderBookManagerClient {
	return &orderBookManagerClient{cc}
}

func (c *orderBookManagerClient) OrderBook(ctx context.Context, in *OrderBookRequest, opts ...grpc.CallOption) (*OrderBookResponse, error) {
	out := new(OrderBookResponse)
	err := c.cc.Invoke(ctx, "/OrderBookManager/OrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderBookManagerClient) Updates(ctx context.Context, in *OrderBookUpdatesRequest, opts ...grpc.CallOption) (OrderBookManager_UpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderBookManager_serviceDesc.Streams[0], "/OrderBookManager/Updates", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderBookManagerUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderBookManager_UpdatesClient interface {
	Recv() (*OrderBookResponse, error)
	grpc.ClientStream
}

type orderBookManagerUpdatesClient struct {
	grpc.ClientStream
}

func (x *orderBookManagerUpdatesClient) Recv() (*OrderBookResponse, error) {
	m := new(OrderBookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderBookManagerServer is the server API for OrderBookManager service.
type OrderBookManagerServer interface {
	OrderBook(context.Context, *OrderBookRequest) (*OrderBookResponse, error)
	Updates(*OrderBookUpdatesRequest, OrderBookManager_UpdatesServer) error
}

func RegisterOrderBookManagerServer(s *grpc.Server, srv OrderBookManagerServer) {
	s.RegisterService(&_OrderBookManager_serviceDesc, srv)
}

func _OrderBookManager_OrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookManagerServer).OrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderBookManager/OrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookManagerServer).OrderBook(ctx, req.(*OrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderBookManager_Updates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderBookUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookManagerServer).Updates(m, &orderBookManagerUpdatesServer{stream})
}

type OrderBookManager_UpdatesServer interface {
	Send(*OrderBookResponse) error
	grpc.ServerStream
}

type orderBookManagerUpdatesServer struct {
	grpc.ServerStream
}

func (x *orderBookManagerUpdatesServer) Send(m *OrderBookResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _OrderBookManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderBookManager",
	HandlerType: (*OrderBookManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderBook",
			Handler:    _OrderBookManager_OrderBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Updates",
			Handler:       _OrderBookManager_Updates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "types.proto",
}
